// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTime() {
  return window['go']['main']['App']['ClearTime']();
}

export function GetRandomAffirmation() {
  return window['go']['main']['App']['GetRandomAffirmation']();
}

export function GetRandomJr() {
  return window['go']['main']['App']['GetRandomJr']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IncrementTime(arg1) {
  return window['go']['main']['App']['IncrementTime'](arg1);
}

export function InitializeAffirmations() {
  return window['go']['main']['App']['InitializeAffirmations']();
}

export function InitializeJrs() {
  return window['go']['main']['App']['InitializeJrs']();
}
